blank_issues_enabled: false
contact_links:
  - name: 📚 Documentación
    url: https://github.com/eddndev/eddn.dev/blob/main/docs/AGENTS.md
    about: Lee la metodología completa del proyecto
  - name: 💬 Discusión
    url: https://github.com/eddndev/eddn.dev/discussions
    about: Para preguntas generales y discusiones
