name: Project Automation

on:
  issues:
    types: [opened, labeled, assigned, closed, reopened]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-add-to-project:
    name: Auto-add issues to project
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/eddndev/projects/2
          github-token: ${{ secrets.PROJECT_PAT }}
          labeled: Sprint:*

  move-to-todo:
    name: Move new issues to Todo
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      github.event.action == 'opened' &&
      !contains(github.event.issue.labels.*.name, 'Epic')
    steps:
      - name: Move to Todo column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: edd n'dev Portfolio - Development
          column: Todo
          repo-token: ${{ secrets.PROJECT_PAT }}

  move-to-in-progress:
    name: Move to In Progress
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      (github.event.action == 'assigned' ||
       (github.event.action == 'labeled' && github.event.label.name == 'Status: In Progress')) &&
      !contains(github.event.issue.labels.*.name, 'Epic')
    steps:
      - name: Move to In Progress column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: edd n'dev Portfolio - Development
          column: In Progress
          repo-token: ${{ secrets.PROJECT_PAT }}

  move-to-done:
    name: Move to Done
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      github.event.action == 'closed' &&
      !contains(github.event.issue.labels.*.name, 'Epic')
    steps:
      - name: Move to Done column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: edd n'dev Portfolio - Development
          column: Done
          repo-token: ${{ secrets.PROJECT_PAT }}

  move-pr-to-review:
    name: Move PR issues to Needs Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Get linked issues
        id: get-issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT }}
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const issueNumbers = body.match(/#(\d+)/g) || [];
            return issueNumbers.map(num => num.replace('#', ''));

      - name: Add Status: Needs Review label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT }}
          script: |
            const issues = ${{ steps.get-issues.outputs.result }};
            for (const issueNumber of issues) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(issueNumber),
                labels: ['Status: Needs Review']
              });
            }
